CREATE SCHEMA IF NOT EXISTS reports;

CREATE TABLE IF NOT EXISTS reports.kpis (
    id UUID PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    value NUMERIC(18,2),
    ts TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
